name: CI Pipeline

on:
  pull_request:
    branches: [main, dev]
  push:
    branches: [dev]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Backend Test (Python)
        run: echo "Backend tests will run here"
      - name: Frontend Build
        run: echo "Frontend build will run here"
